---
- name: rhsatellite_install_master
  src: https://github.com/prometeo-cloud/rhsatellite_install_master

- name: rhsatellite_configure_master
  src: http://192.168.56.112:3000/gogs/rhsatellite_configure_master
#  src: https://github.com/prometeo-cloud/rhsatellite_configure_master
...